### ISSUE TITLE
Usage&Trees: UI Design

### ISSUE THREAD

**Issue by dankelleher** [sunrise-stake/app#108]
UI designs for “trees”

The working idea (designers, feel free to change):

In the working idea, that minting gSOL (depositing SOL) creates a tree, your “home tree”, that may change over time. Trees can grow in size (size of the deposit) and maturity (age of the deposit).

In addition to the home tree, trees appear for people whom you have sent gSOL to, or people who have sent you gSOL. These are “neighbour trees”. They age and change size similarly to the home tree, but are still distinguishable in some way.

One potential option as inspiration: https://www.recarb.earth/

**Comment by ronnyhaase** [comment]
Some ideas:
- A relaxing virtual environment
- Ambient background music loop
- Background effects like blue sky, sunrise & -set, rain, flock of birds passing by with sound
- Visit my tree
- Visit random tree
- Visit "Mother tree" / and or info box with total trees, total and individual offset CO2, etc.
- Highlight and animate tree growth (level-up) since last visit (via cookie?)
